# yaml-language-server: $schema=https://raw.githubusercontent.com/neuro-inc/neuro-flow/refs/heads/master/src/apolo_flow/flow-schema.json
kind: live
title: My flow

defaults:
  life_span: 10d

volumes:
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /root/.ollama
    local: data
  webdata:
    remote: storage:$[[ flow.project_id ]]/web
    mount: /app/backend/data
    local: webdata
  hf_cache:
    remote: storage:ollama_server/cache
    mount: /root/.cache/huggingface

images:
  openwebui:
    ref: image:open-webui:library
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]
    build_preset: cpu-8-20

jobs:
  text_embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:hopper-1.7 # remove "hopper" if not running on H100
    life_span: 10d
    detach: true
    preset: H100x1
    http_port: 80
    http_auth: false

  web:
    image: $[[ images.openwebui.ref ]]
    volumes:
      - ${{ volumes.webdata.ref_rw }}
    http_port: 8080
    preset: cpu-8-20
    detach: true
    browse: true
    env:
      WEBUI_SECRET_KEY: "apolo"
      OPENAI_API_BASE_URL: http://${{ inspect_job(params.server).internal_hostname_named }}:8000/v1 # inspects vllm job in runtime to derive endpoint domain address
      RAG_EMBEDDING_ENGINE: openai
      RAG_OPENAI_API_BASE_URL: http://${{ inspect_job(params.tei).internal_hostname_named }}/v1
    params:
      server: vllm
      tei: text_embeddings

  vllm: # its actually ollama but lets keep the same name
    image: ollama/ollama:0.6.5
    life_span: 10d
    detach: true
    preset: cpu-8-20
    http_port: 8000
    env:
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_KV_CACHE_TYPE: q4_0
      OLLAMA_HOST: "0.0.0.0:8000"
    volumes:
      - $[[ volumes.data.ref_rw ]]
    entrypoint: /bin/bash
    cmd: >
      -c "/bin/ollama serve & sleep 30 && /bin/ollama pull gemma3:4b && wait" 

  # vllm:
  #   image: vllm/vllm-openai:v0.7.2
  #   preset: ${{ params.preset }}
  #   http_port: "8000"
  #   detach: true
  #   volumes:
  #     - ${{ volumes.hf_cache.ref_rw }}
  #   env:
  #     HF_TOKEN: secret:HF_TOKEN # your huggingface token used to pull models, could be added with `apolo secret add HF_TOKEN <token>`
  #   params:
  #     preset: H100x2 # replace the preset during the job startup via `apolo-flow run vllm --param preset <preset-name>`
  #   cmd: >
  #     --model deepseek-ai/DeepSeek-R1-Distill-Llama-70B 
  #     --tokenizer deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  #     --dtype=half
  #     --tensor-parallel-size=2
  #     --max-model-len=10000
